_zombie = _this select 0

~random 1

if !(alive _zombie) then {goto "end"}

_array = ["ryanzombies\sounds\ryanzombiesaggressive1.ogg", "ryanzombies\sounds\ryanzombiesaggressive2.ogg", "ryanzombies\sounds\ryanzombiesaggressive3.ogg", "ryanzombies\sounds\ryanzombiesaggressive4.ogg", "ryanzombies\sounds\ryanzombiesaggressive5.ogg", "ryanzombies\sounds\ryanzombiesaggressive6.ogg", "ryanzombies\sounds\ryanzombiesaggressive7.ogg", "ryanzombies\sounds\ryanzombiesaggressive8.ogg", "ryanzombies\sounds\ryanzombiesaggressive9.ogg", "ryanzombies\sounds\ryanzombiesaggressive10.ogg", "ryanzombies\sounds\ryanzombiesaggressive11.ogg", "ryanzombies\sounds\ryanzombiesaggressive12.ogg", "ryanzombies\sounds\ryanzombiesaggressive13.ogg", "ryanzombies\sounds\ryanzombiesaggressive14.ogg", "ryanzombies\sounds\ryanzombiesaggressive15.ogg", "ryanzombies\sounds\ryanzombiesaggressive16.ogg", "ryanzombies\sounds\ryanzombiesaggressive17.ogg", "ryanzombies\sounds\ryanzombiesaggressive18.ogg", "ryanzombies\sounds\ryanzombiesaggressive19.ogg", "ryanzombies\sounds\ryanzombiesaggressive20.ogg", "ryanzombies\sounds\ryanzombiesaggressive21.ogg", "ryanzombies\sounds\ryanzombiesaggressive22.ogg", "ryanzombies\sounds\ryanzombiesaggressive23.ogg", "ryanzombies\sounds\ryanzombiesaggressive24.ogg", "ryanzombies\sounds\ryanzombiesaggressive25.ogg", "ryanzombies\sounds\ryanzombiesaggressive26.ogg", "ryanzombies\sounds\ryanzombiesaggressive27.ogg", "ryanzombies\sounds\ryanzombiesaggressive28.ogg", "ryanzombies\sounds\ryanzombiesaggressive29.ogg", "ryanzombies\sounds\ryanzombiesaggressive30.ogg", "ryanzombies\sounds\ryanzombiesaggressive31.ogg", "ryanzombies\sounds\ryanzombiesaggressive32.ogg", "ryanzombies\sounds\ryanzombiesaggressive33.ogg", "ryanzombies\sounds\ryanzombiesaggressive34.ogg", "ryanzombies\sounds\ryanzombiesaggressive35.ogg", "ryanzombies\sounds\ryanzombiesaggressive36.ogg", "ryanzombies\sounds\ryanzombiesaggressive37.ogg", "ryanzombies\sounds\ryanzombiesaggressive38.ogg", "ryanzombies\sounds\ryanzombiesaggressive39.ogg", "ryanzombies\sounds\ryanzombiesaggressive40.ogg", "ryanzombies\sounds\ryanzombiesaggressive41.ogg", "ryanzombies\sounds\ryanzombiesaggressive42.ogg", "ryanzombies\sounds\ryanzombiesaggressive43.ogg", "ryanzombies\sounds\ryanzombiesaggressive44.ogg", "ryanzombies\sounds\ryanzombiesaggressive45.ogg", "ryanzombies\sounds\ryanzombiesaggressive46.ogg", "ryanzombies\sounds\ryanzombiesaggressive47.ogg", "ryanzombies\sounds\ryanzombiesaggressive48.ogg"]

_random = _array select floor random count _array

playsound3d [format ["%1",_random], _zombie]

#end